# Generated by Django 4.1.7 on 2023-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_alter_author_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(help_text='date in "mm/dd/yyyy" format'),
        ),
    ]
